plugins:
  - rubocop-rspec
  - rubocop-overhaul

inherit_from:
  - ./oh_defaults/rubocop.yml
  - ./oh_defaults/rubocop-rspec.yml

AllCops:
  TargetRubyVersion: 3.0

Naming/FileName:
 Exclude:
   - lib/rubocop-overhaul.rb

Naming/VariableNumber:
  Enabled: true
  EnforcedStyle: normalcase
