# frozen_string_literal: true

module RuboCop
  module Cop
    module Overhaul
      # Checks that a `consumes` statement is present whenever a `:body`
      # parameter is defined inside an rswag request spec operation block.
      # Without it, the API documentation generated by rswag will not
      # accurately reflect the content type of the request body.
      #
      # @example
      #   # bad
      #   post "Creates a user" do
      #     parameter name: :user, in: :body, schema: { type: :object }
      #   end
      #
      #   # good
      #   post "Creates a user" do
      #     consumes "application/json"
      #     parameter name: :user, in: :body, schema: { type: :object }
      #   end
      #
      #   # good — no :body parameter, so consumes is not required
      #   post "Creates a user" do
      #     parameter name: :page, in: :query, schema: { type: :integer }
      #   end
      #
      class RswagConsumesWithBodyParam < RuboCop::Cop::Base
        MSG = "Add a `consumes` statement when a `:body` parameter is defined."

        # @!method rswag_operation_block?(node)
        def_node_matcher :rswag_operation_block?, <<~PATTERN
          (block
            (send nil? {:get :post :put :patch :delete :head :options} ...)
            (args)
            _)
        PATTERN

        # @!method body_parameter_call?(node)
        def_node_matcher :body_parameter_call?, <<~PATTERN
          (send nil? :parameter (hash <(pair (sym :in) (sym :body)) ...>))
        PATTERN

        # @!method consumes_call?(node)
        def_node_matcher :consumes_call?, <<~PATTERN
          (send nil? :consumes ...)
        PATTERN

        def on_block(node)
          return unless rswag_operation_block?(node)

          body = node.body
          return if body.nil?

          children = body.begin_type? ? body.children : [body]

          has_body_param = children.any? { |child| body_parameter_call?(child) }
          has_consumes   = children.any? { |child| consumes_call?(child) }

          add_offense(node.send_node) if has_body_param && !has_consumes
        end
      end
    end
  end
end
