# frozen_string_literal: true

module RuboCop
  module Cop
    module Overhaul
      # Checks that `produces "application/json"` is present whenever a `schema`
      # is defined inside a `response` block in an rswag request spec operation.
      # Without it, the API documentation generated by rswag will not accurately
      # reflect the content type of the response.
      #
      # @example
      #   # bad
      #   get "Retrieves a list of users" do
      #     response "200", "users found" do
      #       schema type: :array, items: { type: :object }
      #       run_test!
      #     end
      #   end
      #
      #   # good
      #   get "Retrieves a list of users" do
      #     produces "application/json"
      #
      #     response "200", "users found" do
      #       schema type: :array, items: { type: :object }
      #       run_test!
      #     end
      #   end
      #
      #   # good — no schema, so produces is not required
      #   get "Retrieves a list of users" do
      #     response "200", "users found" do
      #       run_test!
      #     end
      #   end
      #
      class RswagProducesWithSchema < RuboCop::Cop::Base
        MSG = 'Add `produces "application/json"` when a `schema` is defined.'

        # @!method rswag_operation_block?(node)
        def_node_matcher :rswag_operation_block?, <<~PATTERN
          (block
            (send nil? {:get :post :put :patch :delete :head :options} ...)
            (args)
            _)
        PATTERN

        # @!method response_block?(node)
        def_node_matcher :response_block?, <<~PATTERN
          (block
            (send nil? :response ...)
            ...)
        PATTERN

        # @!method has_schema_call?(node)
        def_node_matcher :has_schema_call?, <<~PATTERN
          (send nil? :schema ...)
        PATTERN

        # @!method has_produces_json_call?(node)
        def_node_matcher :has_produces_json_call?, <<~PATTERN
          (send nil? :produces (str "application/json") ...)
        PATTERN

        def on_block(node)
          return unless rswag_operation_block?(node)
          return if node.body.nil?

          has_schema   = node.each_descendant(:block).any? do |blk|
            response_block?(blk) && blk.each_descendant(:send).any? { |s| has_schema_call?(s) }
          end
          has_produces = node.each_descendant(:send).any? { |child| has_produces_json_call?(child) }

          add_offense(node.send_node) if has_schema && !has_produces
        end
      end
    end
  end
end
