---
Overhaul/MutableReformDefaults:
  Description: Detect usage of mutable defaults within Reform objects defaults.
  Enabled: true
  Include:
    - app/concepts/**/*.rb
  VersionAdded: '0.0.1'
Overhaul/AssignmentInsteadOfComparison:
  Description: Detect enumerable comparison blocks returning an assignment.
  Enabled: true
  VersionAdded: '0.0.1'
Overhaul/SemanticLoggerContract:
  Description: Detect logger usage incompatible with Semantic Logger
  Enabled: true
  VersionAdded: '0.0.1'
